### ISSUE TITLE
Building image fails with Permission denied

### ISSUE THREAD

**Issue by golharam** [Sentieon/sentieon-amazon-omics#1]
https://github.com/Sentieon/sentieon-amazon-omics/blob/c1043222fb7fe7ddc327a9b4f5da633793096a94/container/sentieon_omics.dockerfile#L124

The last step of this build fails:

```
Step 32/32 : RUN sentieon driver --help &&     igzip --help &&     samtools --help &&     bcftools --help &&     bedtools --help &&     aws --version
 ---> Running in acfe87d4f54b
/bin/sh: /opt/sentieon/sentieon-genomics-202112.07/bin/sentieon: Permission denied
The command '/bin/sh -c sentieon driver --help &&     igzip --help &&     samtools --help &&     bcftools --help &&     bedtools --help &&     aws --version' returned a non-zero code: 126
```

I changed the previous line to:

```
RUN cd /opt/sentieon/sentieon-genomics-${SENTIEON_VERSION}/bin/ && \
    mv bwa bwa.orig && \
    mv minimap2 minimap2.orig && \
    mv sentieon sentieon.orig && \
    mv STAR STAR.orig && \
    ln -s omics_credentials.sh bwa && \
    ln -s omics_credentials.sh minimap2 && \
    ln -s omics_credentials.sh sentieon && \
    ln -s omics_credentials.sh STAR && \
    chmod ugo+x /opt/sentieon/sentieon-genomics-${SENTIEON_VERSION}/bin/sentieon
```

**Comment by DonFreed** [comment]
Thank you for the suggestion. Can you check to see if the `omics_credentials.sh` script is marked as executable?

In the `replace_shell` branch, this file has the executable bit set in GitHub. The executable permission should be preserved when the file is copied into the container image.

**Comment by golharam** [comment]
You are right, it's not.  I actually am embedding the dockerfile and shell script from this repo into my own hence the scripts were not set as executable.  That also explains why I had to make them executable
