### ISSUE TITLE
replace_shell has conflict with master

### ISSUE THREAD

**Issue by golharam** [Sentieon/sentieon-amazon-omics#2]
I was previously testing Omics support with replace_shell as we need to keep our docker images and workflows compatible across workflow execution platforms.  I'd like to get the latest changes from master into replace_shell or at least reconcile the differences.

**Comment by DonFreed** [comment]
Happy to help here. Commits from `master` are merged into `replace_shell` with https://github.com/Sentieon/sentieon-amazon-omics/commit/fe349a794859535c711675601c3593b1ab5c8bef.
