### ISSUE TITLE
Command 'ps' required by nextflow to collect task metrics cannot be found

### ISSUE THREAD

**Issue by amalthomas14** [Sentieon/sentieon-amazon-omics#3]
Nextflow pipelines need a process status command (ps) for generating metrics/trace/reports. It is good to include this in the Sentieon container. 

This can be achieved by adding the following lines to container/sentieon_omics.dockerfile

RUN yum update -y && yum install -y procps

COPY --from=builder /usr/bin/ps /usr/bin/ps

**Comment by DonFreed** [comment]
Thanks for the suggestion! This is fixed in #4.
